### ISSUE TITLE
Feedback: Exercise 2

### ISSUE THREAD

**Issue by jakobnissen** [FSGade/julia_course#2]
2.1 - 2.3: Excellent! Do you understand how the `open("path") do file` syntax work in Julia? What actually happens is that the `do` creates a new *function* which is then passed into the `open` function. So the following two are equivalent:
```
foo = open("path") do file
    read(file)
end

foo = open(read, "path")
``` 

2.4-2.9: Excellent, too. I see you master both the `&&` syntax and the `x ? y : z` syntax. However, here you should probably leverage what I just wrote about the `do` syntax. For example, you could solve it like this:
```
function column_stats(column_file)
    lc, sum, neg, pos, zer = 0, 0, 0, 0, 0
    max_num, min_num = -Inf, Inf
    for ln in eachline(column_file)
        ln_num = parse(Float64, chomp(ln))
        (ln_num > 0) ? pos += 1 : (ln_num < 0) ? neg += 1 : zer += 1
        (ln_num > max_num) && (max_num = ln_num)
        (ln_num < min_num) && (min_num = ln_num)
        lc += 1
        sum += ln_num
    end
    sum / lc, sum, lc, neg, pos, zer, max_num, min_num
end

for i = 1:3
    open(column_stats, "ex1.dat.$i")
end
```
(except you should not forget to also print what each returned number means). The advantage is that first, you don't make the same function three times, and second, you could re-use `column_stats`. In fact, with a very small tweaking, you could also make the same function work for an array of strings instead of a file!

One final thing: Your code should also work on empty files.

2.10: You miss that one.

**Comment by FSGade** [comment]
2.1-2.3: Thank you for showing me of the `open(func, file)` syntax - I was not previously aware of it. I was somewhat aware of the `do` syntax, but not fully. Thanks for the explanation.

2.4-2.9: When you are saying this could easily be generalised to work an array of strings, I can see that you may change the function to only accept arrays, but can you make it accept both? Is there some simple syntax that works for both files and arrays, or would one have to define two versions of the function, where each has different initialisations?
